# question1

In [ ]:
Scrape the details of most viewed videos on YouTube from Wikipedia. 
Url =https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos You need to find following details:
A) Rank
B) Name
C) Artist
D) Upload date
E) Views

In [1]:
! pip install selenium

Requirement already satisfied: selenium in c:\users\nandh\anaconda3\lib\site-packages (4.10.0)
Requirement already satisfied: certifi>=2021.10.8 in c:\users\nandh\anaconda3\lib\site-packages (from selenium) (2022.9.14)
Requirement already satisfied: trio-websocket~=0.9 in c:\users\nandh\anaconda3\lib\site-packages (from selenium) (0.10.3)
Requirement already satisfied: urllib3[socks]<3,>=1.26 in c:\users\nandh\anaconda3\lib\site-packages (from selenium) (1.26.11)
Requirement already satisfied: trio~=0.17 in c:\users\nandh\anaconda3\lib\site-packages (from selenium) (0.22.2)
Requirement already satisfied: idna in c:\users\nandh\anaconda3\lib\site-packages (from trio~=0.17->selenium) (3.3)
Requirement already satisfied: exceptiongroup>=1.0.0rc9 in c:\users\nandh\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.1.2)
Requirement already satisfied: attrs>=20.1.0 in c:\users\nandh\anaconda3\lib\site-packages (from trio~=0.17->selenium) (21.4.0)
Requirement already satisfied: outcome in c:\users\nandh\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.2.0)
Requirement already satisfied: sortedcontainers in c:\users\nandh\anaconda3\lib\site-packages (from trio~=0.17->selenium) (2.4.0)
Requirement already satisfied: sniffio in c:\users\nandh\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.2.0)
Requirement already satisfied: cffi>=1.14 in c:\users\nandh\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.15.1)
Requirement already satisfied: wsproto>=0.14 in c:\users\nandh\anaconda3\lib\site-packages (from trio-websocket~=0.9->selenium) (1.2.0)
Requirement already satisfied: PySocks!=1.5.7,<2.0,>=1.5.6 in c:\users\nandh\anaconda3\lib\site-packages (from urllib3[socks]<3,>=1.26->selenium) (1.7.1)
Requirement already satisfied: pycparser in c:\users\nandh\anaconda3\lib\site-packages (from cffi>=1.14->trio~=0.17->selenium) (2.21)
Requirement already satisfied: h11<1,>=0.9.0 in c:\users\nandh\anaconda3\lib\site-packages (from wsproto>=0.14->trio-websocket~=0.9->selenium) (0.14.0)

In [2]:
import selenium

In [3]:
from selenium import webdriver

In [4]:
import warnings
warnings.filterwarnings("ignore")
import time
from selenium.webdriver.common.by import By

In [5]:
from selenium.common.exceptions import NoSuchElementException

In [20]:
driver = webdriver.Chrome()

driver.get("https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos")

In [21]:
url=[]

title_url=driver.find_elements(By.XPATH,'//table[@class="wikitable sortable jquery-tablesorter"]//tbody//tr//td[2]')

for i in title_url:
    url.append(i.text)

In [22]:
print(len(url))

50

In [23]:
name=[]
names=driver.find_elements(By.XPATH,'//table[@class="wikitable sortable jquery-tablesorter"]//tbody//tr//td[3]')

for i in names:
    name.append(i.text)

In [24]:
print(len(name))

50

In [25]:
rank=[]
ranks=driver.find_elements(By.XPATH,'//table[@class="wikitable sortable jquery-tablesorter"]//tbody//tr//td[4]')
for i in ranks:
    rank.append(i.text)
print(len(rank))

50

In [26]:
publisher=[]
publish=driver.find_elements(By.XPATH,'//table[@class="wikitable sortable jquery-tablesorter"]//tbody//tr//td[5]')
for i in publish:
    publisher.append(i.text)

print(len(publisher))

50

In [27]:
import pandas as pd
pdf=pd.DataFrame({"Video_name":url,"Uploader":name,"Views":rank,"Publication_date":publisher})
pdf

,Video_name,Uploader,Views,Publication_date
0,"""Baby Shark Dance""[6]",Pinkfong Baby Shark - children's songs,13.18,"June 17, 2016"
1,"""Despacito""[9]",Luis Fonsi,8.23,"January 12, 2017"
2,"""Johny Johny Yes Papa""[16]",LooLoo Kids - nursery rhymes,6.76,"October 8, 2016"
3,"""Bath Song""[17]",Cocomelon - nursery rhymes,6.33,"May 2, 2018"
4,"""Shape of You""[18]",Ed Sheeran,6.05,"January 30, 2017"
5,"""See You Again""[21]",Wiz Khalifa,5.98,"April 6, 2015"
6,"""Wheels on the Bus""[26]",Cocomelon - nursery rhymes,5.46,"May 24, 2018"
7,"""Phonics Song with Two Words""[27]",ChuChu TV - children's songs,5.42,"March 6, 2014"
8,"""Uptown Funk""[28]",Mark Ronson,4.99,"November 19, 2014"
9,"""Learning Colors – Colorful Eggs on a Farm""[29]",Miroshka TV - children's songs,4.94,"February 27, 2018"
10,"""Gangnam Style""[30]",Psy,4.86,"July 15, 2012"
11,"""Masha and the Bear – Recipe for Disaster""[35]",Get Movies - children's songs,4.55,"January 31, 2012"
12,"""Dame Tu Cosita""[36]",El Chombo,4.41,"April 5, 2018"
13,"""Axel F""[37]",Crazy Frog,4.00,"June 16, 2009"
14,"""Sugar""[38]",Maroon 5,3.91,"January 14, 2015"
15,"""Roar""[39]",Katy Perry,3.84,"September 5, 2013"
16,"""Counting Stars""[40]",OneRepublic,3.84,"May 31, 2013"
17,"""Baa Baa Black Sheep""[41]",Cocomelon - nursery rhymes,3.73,"June 25, 2018"
18,"""Sorry""[42]",Justin Bieber,3.69,"October 22, 2015"
19,"""Waka Waka (This Time for Africa)""[43]",Shakira,3.68,"June 4, 2010"
20,"""Thinking Out Loud""[44]",Ed Sheeran,3.63,"October 7, 2014"
21,"""Lakdi Ki Kathi""[45]",Jingle Toons,3.63,"June 14, 2018"
22,"""Dark Horse""[46]",Katy Perry,3.56,"February 20, 2014"
23,"""Perfect""[47]",Ed Sheeran,3.51,"November 9, 2017"
24,"""Faded""[48]",Alan Walker,3.49,"December 3, 2015"
25,"""Let Her Go""[49]",Passenger,3.48,"July 25, 2012"
26,"""Humpty the train on a fruits ride""[50]",Kiddiestv Hindi - children's songs,3.51,"January 26, 2018"
27,"""Girls Like You""[51]",Maroon 5,3.45,"May 31, 2018"
28,"""Bailando""[52]",Enrique Iglesias,3.43,"April 11, 2014"
29,"""Lean On""[53]",Major Lazer,3.43,"March 22, 2015"
30,Pinkfong Baby Shark - Kids' Songs & Stories,"7,046,700,000","June 17, 2016","November 2, 2020"
31,Luis Fonsi,"2,993,700,000","January 12, 2017","August 4, 2017"
32,Wiz Khalifa,"2,894,000,000","April 6, 2015","July 10, 2017"
33,Psy,"803,700,000","July 15, 2012","November 24, 2012"
34,Justin Bieber,"245,400,000","February 19, 2010","July 16, 2010"
35,Lady Gaga,"178,400,000","November 24, 2009","April 14, 2010"
36,HDCYT,"128,900,000","May 22, 2007","October 25, 2009"
37,Judson Laipply,"118,900,000","April 6, 2006","May 2, 2009"
38,RCA Records,"92,600,000","February 27, 2007","July 17, 2008"
39,Judson Laipply,"78,400,000","April 6, 2006","March 15, 2008"
40,CLARUSBARTEL72,"76,600,000","April 9, 2007","March 1, 2008"
41,Judson Laipply,"10,600,000","April 6, 2006","May 19, 2006"
42,Smosh,"4,300,000","November 28, 2005","March 12, 2006"
43,eggtea,"2,700,000","January 31, 2006","February 18, 2006"
44,mugenized,"3,400,000","December 1, 2005","January 21, 2006"
45,youtubedude,"2,300,000","December 18, 2005","January 9, 2006"
46,joeB,"1,000,000","October 21, 2005","December 10, 2005"
47,Nikesoccer,"255,000","October 21, 2005","October 31, 2005"
48,larfus,"247,000","October 5, 2005","October 29, 2005"
49,jawed,1,"April 23, 2005","April 23, 2005"

# question2

In [ ]:
Scrape the details team India’s international fixtures from bcci.tv.
Url = https://www.bcci.tv/.
You need to find following details:
A) Match title (I.e. 1 ODI)
B) Series
C) Place
D) Date
E) Time
Note: - From bcci.tv home page you have reach to the international fixture page through code.

In [26]:
driver = webdriver.Chrome()

driver.get(" https://www.bcci.tv/")

In [27]:
fixture_link = driver.find_element(By.XPATH, '/html/body/nav/div[1]/div[2]/ul[1]/li[2]/a')
fixture_url = fixture_link.get_attribute('href')

In [28]:
driver.get(fixture_url)

In [32]:
series=[]
match=driver.find_elements(By.XPATH,'//h5[@class="match-tournament-name ng-binding"]')
for i in match:
    series.append(i.text)

In [33]:
print(len(series))

8

In [38]:
match_title=[]
match=driver.find_elements(By.XPATH,'//span[@class="matchOrderText ng-binding ng-scope"]')
for i in match:
    match_title.append(i.text)
print(len(match_title))

8

In [39]:
place=[]
places=driver.find_elements(By.XPATH,'//span[@class="ng-binding"]')
for i in places:
    place.append(i.text)
print(len(place))

8

In [40]:
time=[]
times=driver.find_elements(By.XPATH,'//div[@class="match-time no-margin ng-binding"]')
for i in times:
    time.append(i.text)
print(len(time))

8

In [41]:
date=[]
dates=driver.find_elements(By.XPATH,'//div[@class="match-dates ng-binding"]')
for i in dates:
    date.append(i.text)
print(len(date))

8

In [44]:
import pandas as pd
pdf=pd.DataFrame({"SERIES":series,"MATCH_TITLE":match_title,"PLACE":place,"DATE":date,"TIME":time})
pdf

,SERIES,MATCH_TITLE,PLACE,DATE,TIME
0,INDIA TOUR OF IRELAND 2023,1st T20I -,Dublin,18 AUG 2023,7:30 PM IST
1,INDIA TOUR OF IRELAND 2023,2nd T20I -,Dublin,20 AUG 2023,7:30 PM IST
2,INDIA TOUR OF IRELAND 2023,3rd T20I -,Dublin,23 AUG 2023,7:30 PM IST
3,ASIA CUP 2023,1st ODI -,Pallekele,2 SEP 2023,10:00 AM IST
4,ASIA CUP 2023,2nd ODI -,Pallekele,4 SEP 2023,10:00 AM IST
5,AUSTRALIA TOUR OF INDIA 2023-24,1st ODI -,Mohali,22 SEP 2023,1:30 PM IST
6,AUSTRALIA TOUR OF INDIA 2023-24,2nd ODI -,Indore,24 SEP 2023,1:30 PM IST
7,AUSTRALIA TOUR OF INDIA 2023-24,3rd ODI -,Rajkot,27 SEP 2023,1:30 PM IST

# question3

In [ ]:
Scrape the details of State-wise GDP of India from statisticstime.com.
Url = http://statisticstimes.com/
You have to find following details: 
A)Rank
B) State
C) GSDP(18-19)- at current prices
D) GSDP(19-20)- at current prices
E) Share(18-19)
F) GDP($ billion)
Note: - From statisticstimes home page you have to reach to economy page through code.

In [28]:
driver=webdriver.Chrome()
driver.get('http://statisticstimes.com/')

In [51]:
economy_link = driver.find_element(By.XPATH, '/html/body/div[2]/div[1]/div[2]/div[2]/button')
economy_link.click()

In [52]:
gdp_states_link = driver.find_element(By.XPATH, '/html/body/div[2]/div[2]/div[2]/ul/li[1]/a')
gdp_states_link.click()

In [31]:
STATE=[]
state=driver.find_elements(By.XPATH,'//div[@class="dataTables_wrapper"]//tbody//tr//td[2]')
for i in state[0:33]:
    STATE.append(i.text)

In [32]:
print(len(STATE))

33

In [34]:
GSDP18_19=[]
gsdp=driver.find_elements(By.XPATH,'//div[@class="dataTables_wrapper"]//tbody//tr//td[4]')
for i in gsdp[0:33]:
    GSDP18_19.append(i.text)
print(len(GSDP18_19))

33

In [35]:
SHARE=[]
share=driver.find_elements(By.XPATH,'//div[@class="dataTables_wrapper"]//tbody//tr//td[5]')
for i in share[0:33]:
    SHARE.append(i.text)
print(len(SHARE))

33

In [37]:
BILLION=[]
billion=driver.find_elements(By.XPATH,'//div[@class="dataTables_wrapper"]//tbody//tr//td[6]')
for i in billion[0:33]:
    BILLION.append(i.text)
print(len(BILLION))

33

In [40]:
rank=[]
ranks=driver.find_elements(By.XPATH,'//div[@class="dataTables_wrapper"]//tbody//tr//td[1]')
for i in ranks[0:33]:
    rank.append(i.text)
print(len(rank))

33

In [41]:
import pandas as pd
pdf=pd.DataFrame({"State":STATE,"Rank":rank,"GSDP18_19":GSDP18_19,"SHARE18_19":SHARE,"BILLION_$":BILLION})
pdf

                        State Rank  GSDP18_19 SHARE18_19 BILLION_$
0                 Maharashtra    1  2,632,792     13.94%   399.921
1                  Tamil Nadu    2  1,630,208      8.63%   247.629
2               Uttar Pradesh    3  1,584,764      8.39%   240.726
3                     Gujarat    4  1,502,899      7.96%   228.290
4                   Karnataka    5  1,493,127      7.91%   226.806
5                 West Bengal    6  1,089,898      5.77%   165.556
6                   Rajasthan    7    942,586      4.99%   143.179
7              Andhra Pradesh    8    862,957      4.57%   131.083
8                   Telangana    9    861,031      4.56%   130.791
9              Madhya Pradesh   10    809,592      4.29%   122.977
10                     Kerala   11    781,653      4.14%   118.733
11                      Delhi   12    774,870      4.10%   117.703
12                    Haryana   13    734,163      3.89%   111.519
13                      Bihar   14    530,363      2.81%    80.562
14                     Punjab   15    526,376      2.79%    79.957
15                     Odisha   16    487,805      2.58%    74.098
16                      Assam   17    315,881      1.67%    47.982
17               Chhattisgarh   18    304,063      1.61%    46.187
18                  Jharkhand   19    297,204      1.57%    45.145
19                Uttarakhand   20    245,895      1.30%    37.351
20            Jammu & Kashmir   21    155,956      0.83%    23.690
21           Himachal Pradesh   22    153,845      0.81%    23.369
22                        Goa   23     73,170      0.39%    11.115
23                    Tripura   24     49,845      0.26%     7.571
24                 Chandigarh   25     42,114      0.22%     6.397
25                 Puducherry   26     34,433      0.18%     5.230
26                  Meghalaya   27     33,481      0.18%     5.086
27                     Sikkim   28     28,723      0.15%     4.363
28                    Manipur   29     27,870      0.15%     4.233
29                   Nagaland   30     27,283      0.14%     4.144
30          Arunachal Pradesh   31     24,603      0.13%     3.737
31                    Mizoram   32     22,287      0.12%     3.385
32  Andaman & Nicobar Islands   33          -          -         -

# question4

In [ ]:
Scrape the details of trending repositories on Github.com.
Url = https://github.com/
You have to find the following details:
A) Repository title
B) Repository description
C) Contributors count
D) Language used

In [26]:
driver=webdriver.Chrome()
driver.get("https://github.com/")

In [27]:
explore_menu = driver.find_elements(By.XPATH, '//*[@aria-label="Explore"]')

In [40]:
name=[]

rep_name=driver.find_elements(By.XPATH,'//span[@class="text-normal"]')

for i in rep_name[0:20]:
    name.append(i.text)

In [41]:
print(len(name))

20

In [38]:
description=[]

descrip=driver.find_elements(By.XPATH,'//p[@class="col-9 color-fg-muted my-1 pr-4"]')


for i in descrip[0:20]:
    description.append(i.text)

In [39]:
print(len(description))

20

In [36]:
language=[]

lang=driver.find_elements(By.XPATH,'//span[@class="d-inline-block ml-0 mr-3"]')

for i in lang[0:20]:
    language.append(i.text)

In [37]:
print(len(language))

20

In [43]:
contribution_count=[]
count=driver.find_elements(By.XPATH,'//a[@class="Link Link--muted d-inline-block mr-3"]')

for i in count[0:20]:
    contribution_count.append(i.text)

In [44]:
print(len(contribution_count))

20

In [47]:
import pandas as pd
psf=pd.DataFrame({"Rep_title":name,"Description":description,"Language":language,"Contripution_count":contribution_count})
psf

,Rep_title,Description,Language,Contripution_count
0,getumbrel /,"A self-hosted, offline, ChatGPT-like chatbot. ...",TypeScript,"2,035"
1,elidianaandrade /,Repositório do lab Contribuindo em um Projeto ...,Python,110
2,apple /,This repository contains the official implemen...,Java,414
3,alibaba /,阿里巴巴 MySQL binlog 增量订阅&消费组件,C#,"3,219"
4,LorisYounger /,"虚拟桌宠模拟器 一个开源的桌宠软件, 可以内置到任何WPF应用程序",Rust,"1,035"
5,systeminit /,The System Initiative software,Ruby,57
6,ubicloud /,"Open, free, and portable cloud. Elastic comput...",TypeScript,"26,394"
7,ill-inc /,Biomes is an open source sandbox MMORPG built ...,Go,"7,367"
8,1Panel-dev /,🔥 🔥 🔥 现代化、开源的 Linux 服务器运维管理面板。,Python,"1,363"
9,taojy123 /,类似按键精灵的鼠标键盘录制和自动化操作 模拟点击和键入 | automate mouse c...,Python,138
10,jiran214 /,GPT-vup BIliBili | 抖音 | AI | 虚拟主播,C,455
11,SkyAsor /,Save time and maximize your profits with our J...,Python,29
12,bellard /,Public repository of the QuickJS Javascript En...,JavaScript,774
13,rany2 /,Use Microsoft Edge's online text-to-speech ser...,Python,15
14,ibaiw /,2023 HVV情报速递~,HTML,"1,024"
15,wangshusen /,搜索引擎原理,HTML,109
16,diegomura /,📄 Create PDF files using React,Kotlin,"9,223"
17,roboflow /,We write your reusable computer vision tools. 💜,TypeScript,833
18,xxlllq /,💯2023年系统架构设计师（软考高级）备考资料。,TypeScript,"4,165"
19,opentffoundation /,The OpenTF Manifesto expresses concern over Ha...,Java,692

# question5

In [ ]:
Scrape the details of top 100 songs on billiboard.com. Url = https:/www.billboard.com/
You have to find the following details:
A) Song name
B) Artist name
C) Last week rank
D) Peak rank
E) Weeks on board
Note: - From the home page you have to click on the charts option then hot 100-page link through code.

In [49]:
driver=webdriver.Chrome()
driver.get("https:/www.billboard.com/")

In [50]:
chart=driver.find_element(By.XPATH,'/html/body/div[3]/header/div/div[2]/div/div/div[2]/div[2]/div/div/nav/ul/li[1]')
chart.click()

In [51]:
hot100=driver.find_element(By.XPATH,'/html/body/div[3]/main/div[2]/div[1]/div[1]/div/div/div[1]/div/div[2]/span')
hot100.click()

In [52]:
song_name=[]

name=driver.find_elements(By.XPATH,'//h3[@class="c-title  a-no-trucate a-font-primary-bold-s u-letter-spacing-0021 lrv-u-font-size-18@tablet lrv-u-font-size-16 u-line-height-125 u-line-height-normal@mobile-max a-truncate-ellipsis u-max-width-330 u-max-width-230@tablet-only"]')

for i in name[0:91]:
    song_name.append(i.text)
    
print(len(song_name))

91

In [53]:
artist=[]
name=driver.find_elements(By.XPATH,'//span[@class="c-label  a-no-trucate a-font-primary-s lrv-u-font-size-14@mobile-max u-line-height-normal@mobile-max u-letter-spacing-0021 lrv-u-display-block a-truncate-ellipsis-2line u-max-width-330 u-max-width-230@tablet-only"]')
for i in name[0:91]:
    artist.append(i.text)
print(len(artist))

91

In [54]:
weeks_chart=[]
chart=driver.find_elements(By.XPATH,'//span[@class="c-label  a-font-primary-m lrv-u-padding-tb-050@mobile-max"]')
for i in chart[0:91]:
    weeks_chart.append(i.text)
print(len(weeks_chart))

91

In [55]:
import pandas as pd
pdf=pd.DataFrame({"Song_name":song_name,"Artist_name":artist,"Weeks_of_count":weeks_chart})
pdf

        Song_name                        Artist_name Weeks_of_count
0        Fast Car                         Luke Combs              2
1    Cruel Summer                       Taylor Swift              2
2       Calm Down                Rema & Selena Gomez             20
3        Fukumean                              Gunna
4         Vampire                     Olivia Rodrigo
..            ...                                ...            ...
86        Save Me      Jelly Roll With Lainey Wilson             19
87  God's Country                       Travis Scott
88   I'm Just Ken                       Ryan Gosling
89            ICU                         Coco Jones
90         Skitzo  Travis Scott Featuring Young Thug             33

[91 rows x 3 columns]

# question6

In [ ]:
Url = https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey-
You have to find the following details:
    6. Scrape the details of Highest selling novels.
compare
A) Book name
B) Author name
C) Volumes sold
D) Publisher
E) Genre

In [58]:
driver=webdriver.Chrome()
driver.get(" https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey-you")

In [62]:
search=driver.find_element(By.XPATH,'/html/body/div[1]/header/div/div/gu-island/div/div/div[4]/a')
search.send_keys("highest_selling_novels")

In [63]:
name=[]
names=driver.find_elements(By.XPATH,'//tr[@class="odd"]//td[2]')
for i in names:
    name.append(i.text)

In [64]:
print(len(name))

50

In [65]:
author=[]
name=driver.find_elements(By.XPATH,'//tr[@class="odd"]//td[3]')
for i in name:
    author.append(i.text)
print(len(author))

50

In [66]:
volumes=[]
count=driver.find_elements(By.XPATH,'//tr[@class="odd"]//td[4]')
for i in count:
    volumes.append(i.text)

In [67]:
publisher=[]
publish=driver.find_elements(By.XPATH,'//tr[@class="odd"]//td[5]')
for i in publish:
    publisher.append(i.text)
print(len(publisher))

50

In [68]:
genre=[]
gen=driver.find_elements(By.XPATH,'//tr[@class="odd"]//td[6]')
for i in gen:
    genre.append(i.text)
print(len(genre))

50

In [69]:
import pandas as pd
pdf=pd.DataFrame({"Title":name,"Author":author,"Volumes":volumes,"Publisher":publisher,"Genre":genre})
pdf

,Title,Author,Volumes,Publisher,Genre
0,<selenium.webdriver.remote.webelement.WebEleme...,"Rowling, J.K.","4,475,152",Bloomsbury,Children's Fiction
1,<selenium.webdriver.remote.webelement.WebEleme...,"Rowling, J.K.","4,179,479",Bloomsbury,Children's Fiction
2,<selenium.webdriver.remote.webelement.WebEleme...,"Rowling, J.K.","3,583,215",Bloomsbury,Children's Fiction
3,<selenium.webdriver.remote.webelement.WebEleme...,"Rowling, J.K.","3,377,906",Bloomsbury,Children's Fiction
4,<selenium.webdriver.remote.webelement.WebEleme...,"Rowling, J.K.","2,950,264",Bloomsbury,Children's Fiction
5,<selenium.webdriver.remote.webelement.WebEleme...,"Meyer, Stephenie","2,315,405","Little, Brown Book",Young Adult Fiction
6,<selenium.webdriver.remote.webelement.WebEleme...,"James, E. L.","2,193,928",Random House,Romance & Sagas
7,<selenium.webdriver.remote.webelement.WebEleme...,"Meyer, Stephenie","2,152,737","Little, Brown Book",Young Adult Fiction
8,<selenium.webdriver.remote.webelement.WebEleme...,"Meyer, Stephenie","2,052,876","Little, Brown Book",Young Adult Fiction
9,<selenium.webdriver.remote.webelement.WebEleme...,"Haddon, Mark","1,979,552",Random House,General & Literary Fiction
10,<selenium.webdriver.remote.webelement.WebEleme...,"Bryson, Bill","1,852,919",Transworld,Popular Science
11,<selenium.webdriver.remote.webelement.WebEleme...,"Meyer, Stephenie","1,787,118","Little, Brown Book",Young Adult Fiction
12,<selenium.webdriver.remote.webelement.WebEleme...,"Donaldson, Julia","1,781,269",Pan Macmillan,Picture Books
13,<selenium.webdriver.remote.webelement.WebEleme...,"Hosseini, Khaled","1,629,119",Bloomsbury,General & Literary Fiction
14,<selenium.webdriver.remote.webelement.WebEleme...,"Hosseini, Khaled","1,583,992",Bloomsbury,General & Literary Fiction
15,<selenium.webdriver.remote.webelement.WebEleme...,"Niffenegger, Audrey","1,546,886",Random House,General & Literary Fiction
16,<selenium.webdriver.remote.webelement.WebEleme...,"Fielding, Helen","1,508,205",Pan Macmillan,General & Literary Fiction
17,<selenium.webdriver.remote.webelement.WebEleme...,"Bernieres, Louis de","1,352,318",Random House,General & Literary Fiction
18,<selenium.webdriver.remote.webelement.WebEleme...,"Martel, Yann","1,310,176",Canongate,General & Literary Fiction
19,<selenium.webdriver.remote.webelement.WebEleme...,"Pelzer, Dave","1,217,712",Orion,Autobiography: General
20,<selenium.webdriver.remote.webelement.WebEleme...,"McCourt, Frank","1,204,058",HarperCollins,Autobiography: General
21,<selenium.webdriver.remote.webelement.WebEleme...,"Pullman, Philip","1,181,503",Scholastic Ltd.,Young Adult Fiction
22,<selenium.webdriver.remote.webelement.WebEleme...,"Rowling, J.K.","1,153,181",Bloomsbury,Science Fiction & Fantasy
23,<selenium.webdriver.remote.webelement.WebEleme...,"Parsons, Tony","1,130,802",HarperCollins,General & Literary Fiction
24,<selenium.webdriver.remote.webelement.WebEleme...,"McCall Smith, Alexander","1,115,549","Little, Brown Book","Crime, Thriller & Adventure"
25,<selenium.webdriver.remote.webelement.WebEleme...,"Ahern, Cecelia","1,107,379",HarperCollins,General & Literary Fiction
26,<selenium.webdriver.remote.webelement.WebEleme...,"Zafon, Carlos Ruiz","1,092,349",Orion,General & Literary Fiction
27,<selenium.webdriver.remote.webelement.WebEleme...,"Grisham, John","1,087,262",Random House,"Crime, Thriller & Adventure"
28,<selenium.webdriver.remote.webelement.WebEleme...,"Pullman, Philip","1,037,160",Scholastic Ltd.,Young Adult Fiction
29,<selenium.webdriver.remote.webelement.WebEleme...,"Smith, Delia","1,015,956",Random House,Food & Drink: General
30,<selenium.webdriver.remote.webelement.WebEleme...,"Boyne, John","1,004,414",Random House Childrens Books G,Young Adult Fiction
31,<selenium.webdriver.remote.webelement.WebEleme...,"Pullman, Philip","1,002,314",Scholastic Ltd.,Young Adult Fiction
32,<selenium.webdriver.remote.webelement.WebEleme...,"Gray, John","992,846",HarperCollins,Popular Culture & Media: General Interest
33,<selenium.webdriver.remote.webelement.WebEleme...,"Lewycka, Marina","986,115",Penguin,General & Literary Fiction
34,<selenium.webdriver.remote.webelement.WebEleme...,"Tolkien, J. R. R.","967,466",HarperCollins,Science Fiction & Fantasy
35,<selenium.webdriver.remote.webelement.WebEleme...,"Rubenfeld, Jed","962,515",Headline,"Crime, Thriller & Adventure"
36,<selenium.webdriver.remote.webelement.WebEleme...,"Coelho, Paulo","956,114",HarperCollins,General & Literary Fiction
37,<selenium.webdriver.remote.webelement.WebEleme...,"Bryson, Bill","931,312",Transworld,Travel Writing
38,<selenium.webdriver.remote.webelement.WebEleme...,"Fielding, Helen","924,695",Pan Macmillan,General & Literary Fiction
39,<selenium.webdriver.remote.webelement.WebEleme...,"McKenna, Paul","905,086",Transworld,Fitness & Diet
40,<selenium.webdriver.remote.webelement.WebEleme...,"Grisham, John","869,671",Random House,"Crime, Thriller & Adventure"
41,<selenium.webdriver.remote.webelement.WebEleme...,"Lawson, Nigella","862,602",Random House,Food & Drink: General
42,<selenium.webdriver.remote.webelement.WebEleme...,"Edwards, Kim","845,858",Penguin,General & Literary Fiction
43,<selenium.webdriver.remote.webelement.WebEleme...,"Hornby, Nick","828,215",Penguin,General & Literary Fiction
44,<selenium.webdriver.remote.webelement.WebEleme...,"Dawkins, Richard","816,907",Transworld,Popular Science
45,<selenium.webdriver.remote.webelement.WebEleme...,"Smith, Zadie","815,586",Penguin,General & Literary Fiction
46,<selenium.webdriver.remote.webelement.WebEleme...,"Zusak, Markus","809,641",Transworld,General & Literary Fiction
47,<selenium.webdriver.remote.webelement.WebEleme...,"Harris, Robert","807,311",Random House,General & Literary Fiction
48,<selenium.webdriver.remote.webelement.WebEleme...,"Collins, Suzanne","792,187",Scholastic Ltd.,Young Adult Fiction
49,<selenium.webdriver.remote.webelement.WebEleme...,"Oliver, Jamie","791,095",Penguin,Food & Drink: General

# question7

In [ ]:
Scrape the details most watched tv series of all time from imdb.com.
Url = https://www.imdb.com/list/ls095964455/ You
have to find the following details:
A) Name
B) Year span
C) Genre
D) Run time
E) Ratings
F) Votes

In [95]:
driver=webdriver.Chrome()
driver.get(" https://www.imdb.com/list/ls095964455/")

In [100]:
genre=[]

gen = driver.find_elements(By.XPATH,'//span[@class="runtime"]')

for i in gen:
    genre.append(i)

print(len(genre))

100

In [101]:
year_span=[]

year=driver.find_elements(By.XPATH,'//span[@class="lister-item-year text-muted unbold"]')

for i in year:
    year_span.append(i.text)

print(len(year_span))

100

In [102]:
votes=[]
vote=driver.find_elements(By.XPATH,'//div[@class="lister-item-content"]//p[4]//span[2]')
for i in vote:
    votes.append(i.text)
print(len(votes))

100

In [103]:
heading=[]
heder=driver.find_elements(By.XPATH,'//div[@class="lister-item-content"]//h3')
for i in heder:
    heading.append(i.text)

In [104]:
print(len(heading))

100

In [111]:
time=[]
times=driver.find_elements(By.XPATH,'//div[@class="lister-item-content"]//p//span[5]')
for i in times:
    time.append(i)

In [106]:
print(len(time))

100

In [113]:
genre=[]
gen=driver.find_elements(By.XPATH,'//div[@class="lister-item-content"]//p//span[3]')
for i in gen:
    genre.append(i.text)
print(len(genre))

100

In [115]:
import pandas as pd
pdf=pd.DataFrame({"Title":heading,"Genre":time,"Time":genre,"Votes":votes,"Year_span":year_span})
pdf

,Title,Genre,Time,Votes,Year_span
0,1. Game of Thrones (2011–2019),<selenium.webdriver.remote.webelement.WebEleme...,57 min,"2,193,714",(2011–2019)
1,2. Stranger Things (2016–2024),<selenium.webdriver.remote.webelement.WebEleme...,51 min,"1,267,402",(2016–2024)
2,3. The Walking Dead (2010–2022),<selenium.webdriver.remote.webelement.WebEleme...,44 min,"1,041,263",(2010–2022)
3,4. 13 Reasons Why (2017–2020),<selenium.webdriver.remote.webelement.WebEleme...,60 min,"306,044",(2017–2020)
4,5. The 100 (2014–2020),<selenium.webdriver.remote.webelement.WebEleme...,43 min,"265,116",(2014–2020)
...,...,...,...,...,...
95,96. Reign (2013–2017),<selenium.webdriver.remote.webelement.WebEleme...,42 min,"52,449",(2013–2017)
96,97. A Series of Unfortunate Events (2017–2019),<selenium.webdriver.remote.webelement.WebEleme...,50 min,"64,475",(2017–2019)
97,98. Criminal Minds (2005– ),<selenium.webdriver.remote.webelement.WebEleme...,42 min,"210,150",(2005– )
98,99. Scream: The TV Series (2015–2019),<selenium.webdriver.remote.webelement.WebEleme...,45 min,"43,696",(2015–2019)
99,100. The Haunting of Hill House (2018),<selenium.webdriver.remote.webelement.WebEleme...,572 min,"263,779",(2018)

# question8

In [ ]:
Details of Datasets from UCI machine learning repositories.
Url = https://archive.ics.uci.edu/
You have to find the following details:
A) Dataset name
B) Data type
C) Task
D) Attribute type
E) No of instances
F) No of attribute G) Year
Note: - from the home page you have to go to the Show All Dataset page through code.

In [6]:
driver=webdriver.Chrome()
driver.get("https://archive.ics.uci.edu/")

In [118]:
view_datasets=driver.find_elements(By.XPATH,'/html/body/div/div[1]/div[1]/main/div/div[1]/div/div/div/a[1]')
view_datasets.click()

In [7]:
data_sets=[]
sets=driver.find_elements(By.XPATH,'//h2[@class="truncate text-primary"]')
for i in sets:
    data_sets.append(i.text)
print(len(data_sets))

12

In [8]:
dataset_name=[]
name=driver.find_elements(By.XPATH,'//a[@class="link-hover link text-xl font-semibold"]')
for i in name:
    dataset_name.append(i.text)
print(len(dataset_name))

12

In [9]:
instance=[]

instan=driver.find_elements(By.XPATH,'//div[@class="relative col-span-8 sm:col-span-7"]//div[3]//span')

for i in instan:
    instance.append(i.text)

    
print(len(instance))

12

In [10]:
hreff=[]
hrefs=driver.find_elements(By.XPATH,'//a[@class="link-hover link text-xl font-semibold"]')

for i in hrefs:
    hreff.append(i.get_attribute('href'))

In [11]:
print(len(hreff))

12

In [19]:
JD=[]
for i in hreff:
    driver.get(i)
    try:
        i.find_elements(By.XPATH,'//div[@class="rounded-box bg-base-100"]//div[4]//span[1]')
        JD.append(i.text)
    except NOSuchElementException as e:
        JD.append("none")

NameError: name 'NOSuchElementException' is not defined